### PR TITLE
rm height for selectize (multiple selection)

### PR DESCRIPTION
**Pull request by bthieurmel**
Hi,

Thanks for this great and usefull package. I've observed and fixed that multiple ``selectInput`` are not fully display. Seems due to ``height`` argument : 

with actual css : 

with_height

just removing height

without_height

### CODE REVIEW

**Comment by nik01010** [comment]
Hi bthieurmel,
Thanks for your comments.
Are you able to share the code for your multiple select inputs, so I can understand where this fails and investigate? Controlling text box height was added after a specific request, so want to ensure this continues to work properly.

**Comment by bthieurmel** [comment]
Hi,

You can find the code in this PR in commits part https://github.com/nik01010/dashboardthemes/pull/6/commits/1d442879c35e2a4b99decccd138f950fc18fe12c

I've just remove the ``height`` line, keeping ``min-height``

**Comment by nik01010** [comment]
I meant, are you able to share the code of the shinydashboard you were using when you found this bug, or at least sample code for the selectinput parts. I wanted to better understand where it's failing.

**Comment by bthieurmel** [comment]
Simple example : 

````
library(shiny)
library(shinydashboard)
library(dashboardthemes)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    shinyDashboardThemes(
      theme = "blue_gradient"
    ),
    
    
    selectInput("id", "Multiple choices : ", choices = state.name, 
                selected = state.name[1:10], multiple = TRUE)
  )
)

server <- function(input, output) { }

shinyApp(ui, server)
````

``multiple selectInput`` have a ``min-height`` but must increase when select multiple elements to see all selected values. ``height`` css freezes the size and so we can't see all elements.

**Comment by nik01010** [comment]
Thanks for that example - it's a lot clearer now.
The problem is this change seems to remove the ability to make textboxes smaller, which was originally added because of a request. So I think simply removing the height argument, as you suggested, won't be enough.

**Comment by bthieurmel** [comment]
Yes, seems we can reduce ``textBox`` size, but not ``selectInput`` size... You can fix that for example using separate .css : 


````
          /* textbox */
          .form-control{
            background: ', textboxBackColor, ';
            color: ', appFontColor, ';
            border-color: ', textboxBorderColor, ';
            border-radius: ', textboxBorderRadius, 'px;
            min-height: ', textboxHeight, 'px;
            height: ', textboxHeight, 'px;
            padding: ', textboxPadding, ';
          }

          /* select */
          .selectize-input, .selectize-control.single .selectize-input {
            background: ', textboxBackColor, ';
            color: ', appFontColor, ';
            border-color: ', textboxBorderColor, ';
            border-radius: ', textboxBorderRadius, 'px;
            min-height: ', textboxHeight, 'px;
            padding: ', textboxPadding, ';
          }

          /* textbox & slider : selected */
          .form-control:focus, .selectize-input.focus {
            color: ', appFontColor, ';
            background: ', textboxBackColorSelect, ';
            border-color: ', textboxBorderColorSelect, ';
            -webkit-box-shadow: inset 0px 0px 0px, 0px 0px 0px;
            box-shadow: inset 0px 0px 0px, 0px 0px 0px;
          }
````

**Comment by nik01010** [comment]
This issue has (belatedly) been fixed in PR #15

**Pull request closed without merging**
